apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-api
  labels:
    app: credit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-api
  template:
    metadata:
      labels:
        app: credit-api
    spec:
      containers:
      - name: credit-api
        image: 220192014943.dkr.ecr.us-east-2.amazonaws.com/mercado-libre-ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 80m
            memory: 100Mi
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        env:
          - name: DB_USERNAME
            value: #{DB_USERNAME}#
          - name: DB_PASSWORD
            value: #{DB_PASSWORD}#
          - name: DB_TABLE
            value: #{DB_TABLE}#
          - name: DB_DB
            value: #{DB_DB}#
          - name: DB_HOST
            value: #{DB_HOST}#

