apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercado-libre-challange-api
  labels:
    app: mercado-libre-challange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mercado-libre-challange
  template:
    metadata:
      labels:
        app: mercado-libre-challange
    spec:
      containers:
      - name: mercado-libre-challange
        image: 220192014943.dkr.ecr.us-east-2.amazonaws.com/mercado-libre-ecr:980f6939c374a3264b928f0b1f03c8a57581e825
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 